export type AccountIconOption = { name: string; label: string };
export type AccountIconGroup = { title: string; icons: AccountIconOption[] };

function iconLabel(name: string) {
  return name
    .replace(/^material:/, "")
    .split(/[_-]+/)
    .map((word) => (word ? `${word[0].toUpperCase()}${word.slice(1)}` : word))
    .join(" ");
}

function materialIcons(names: string[]): AccountIconOption[] {
  return names.map((name) => ({
    name: `material:${name}`,
    label: iconLabel(name),
  }));
}

function materialGroup(title: string, names: string[]): AccountIconGroup {
  return { title, icons: materialIcons(names) };
}

export const ACCOUNT_ICON_GROUPS: AccountIconGroup[] = [
  {
    title: "Money & accounts",
    icons: [
      { name: "credit-card", label: "Card" },
      { name: "bank", label: "Bank" },
      { name: "cash", label: "Cash" },
      { name: "wallet", label: "Wallet" },
      { name: "piggy-bank", label: "Savings" },
      { name: "currency-exchange", label: "Currency" },
      ...materialIcons([
        "paid",
        "credit_score",
        "attach_money",
        "request_quote",
        "receipt_long",
        "price_check",
        "money_bag",
        "point_of_sale",
        "send_money",
        "swap_horiz",
        "compare_arrows",
        "account_tree",
        "move_up",
        "move_down",
      ]),
    ],
  },
  {
    title: "Everyday spending",
    icons: [
      { name: "home", label: "Home & bills" },
      { name: "shopping", label: "Shopping" },
      { name: "food", label: "Food & dining" },
      { name: "coffee", label: "Coffee" },
      { name: "car", label: "Transport & travel" },
      { name: "account", label: "Family & personal" },
      ...materialIcons([
        "cleaning_services",
        "child_care",
        "pets",
        "local_laundry_service",
        "checkroom",
        "dry_cleaning",
        "fitness_center",
        "self_care",
        "mobile",
        "computer",
        "local_mall",
        "package_2",
        "calendar_month",
        "schedule",
      ]),
    ],
  },
  {
    title: "Goals & interests",
    icons: [
      { name: "trophy", label: "Goals" },
      { name: "camera", label: "Photography" },
      { name: "shield-check", label: "Emergency fund" },
      { name: "trending-up", label: "Investments" },
      { name: "bell", label: "Subscriptions" },
      { name: "format-paint", label: "Art & hobbies" },
      ...materialIcons([
        "flag",
        "sports_esports",
        "music_note",
        "hiking",
        "volunteer_activism",
        "favorite",
        "celebration",
        "workspace_premium",
        "target",
        "rocket_launch",
        "psychology",
        "eco",
        "star",
        "trophy",
      ]),
    ],
  },
  materialGroup("Entertainment", [
    "movie",
    "theaters",
    "live_tv",
    "tv",
    "music_note",
    "headphones",
    "sports_esports",
    "casino",
    "celebration",
    "nightlife",
    "festival",
    "attractions",
    "comedy_mask",
    "local_activity",
    "confirmation_number",
    "stadium",
    "sports_soccer",
    "sports_basketball",
    "podcasts",
    "playing_cards",
  ]),
  materialGroup("Food", [
    "restaurant",
    "lunch_dining",
    "dinner_dining",
    "breakfast_dining",
    "brunch_dining",
    "local_cafe",
    "local_bar",
    "bakery_dining",
    "fastfood",
    "ramen_dining",
    "rice_bowl",
    "soup_kitchen",
    "kebab_dining",
    "egg_alt",
    "icecream",
    "cake",
    "local_pizza",
    "liquor",
    "tapas",
    "outdoor_grill",
  ]),
  materialGroup("Groceries", [
    "shopping_cart",
    "shopping_basket",
    "grocery",
    "shopping_bag",
    "nutrition",
    "egg",
    "cookie",
    "set_meal",
    "shopping_cart_checkout",
    "barcode_scanner",
    "qr_code_scanner",
    "scale",
    "eco",
    "compost",
    "recycling",
    "package_2",
    "inventory_2",
    "receipt_long",
    "sell",
    "storefront",
  ]),
  materialGroup("Subscriptions", [
    "subscriptions",
    "autorenew",
    "sync",
    "event_repeat",
    "calendar_month",
    "credit_card",
    "payments",
    "receipt_long",
    "notifications_active",
    "mail",
    "newspaper",
    "cloud",
    "storage",
    "wifi",
    "mobile",
    "live_tv",
    "music_note",
    "podcasts",
    "workspace_premium",
    "verified",
  ]),
  materialGroup("Transportation", [
    "directions_car",
    "directions_bus",
    "train",
    "subway",
    "tram",
    "two_wheeler",
    "pedal_bike",
    "electric_scooter",
    "flight",
    "local_taxi",
    "local_shipping",
    "commute",
    "traffic",
    "ev_station",
    "local_gas_station",
    "tire_repair",
    "car_repair",
    "local_parking",
    "navigation",
    "route",
  ]),
  materialGroup("Travel", [
    "flight_takeoff",
    "flight_land",
    "luggage",
    "travel_explore",
    "hotel",
    "bed",
    "beach_access",
    "map",
    "public",
    "language",
    "passport",
    "hiking",
    "sailing",
    "directions_boat",
    "train",
    "car_rental",
    "photo_camera",
    "restaurant",
    "local_activity",
    "explore",
  ]),
  materialGroup("Rent", [
    "home",
    "apartment",
    "house",
    "real_estate_agent",
    "key",
    "door_open",
    "contract",
    "receipt_long",
    "payments",
    "calendar_month",
    "event_repeat",
    "location_city",
    "domain",
    "holiday_village",
    "cottage",
    "bedroom_parent",
    "kitchen",
    "chair",
    "garage",
    "other_houses",
  ]),
  materialGroup("Health", [
    "local_hospital",
    "medical_services",
    "health_and_safety",
    "medication",
    "vaccines",
    "stethoscope",
    "cardiology",
    "dentistry",
    "ophthalmology",
    "dermatology",
    "psychology",
    "fitness_center",
    "exercise",
    "nutrition",
    "monitor_heart",
    "emergency",
    "healing",
    "pill",
    "ambulance",
    "bloodtype",
  ]),
  materialGroup("Education", [
    "school",
    "menu_book",
    "auto_stories",
    "library_books",
    "book_2",
    "calculate",
    "science",
    "experiment",
    "psychology",
    "history_edu",
    "draw",
    "edit_note",
    "computer",
    "code",
    "language",
    "translate",
    "quiz",
    "task_alt",
    "cast_for_education",
    "co_present",
  ]),
  materialGroup("Utilities", [
    "bolt",
    "water_drop",
    "gas_meter",
    "electric_meter",
    "water_damage",
    "lightbulb",
    "phone_enabled",
    "wifi",
    "router",
    "cable",
    "power",
    "thermostat",
    "heat_pump",
    "ac_unit",
    "local_fire_department",
    "delete",
    "recycling",
    "cleaning_services",
    "plumbing",
    "construction",
  ]),
  materialGroup("Other", [
    "category",
    "more_horiz",
    "help",
    "info",
    "star",
    "favorite",
    "label",
    "bookmark",
    "pin_drop",
    "event",
    "schedule",
    "person",
    "group",
    "work",
    "business_center",
    "description",
    "folder",
    "inventory_2",
    "package_2",
    "public",
  ]),
  {
    title: "More",
    icons: [
      { name: "clock", label: "Scheduled payments" },
      { name: "help", label: "Other" },
      { name: "weather-night", label: "Nightlife" },
      { name: "experiment", label: "Education" },
      { name: "backup", label: "Backup fund" },
      { name: "photo-library", label: "Media" },
      ...materialIcons([
        "category",
        "bookmark",
        "dashboard",
        "folder",
        "description",
        "inventory_2",
        "public",
        "language",
        "map",
        "event",
        "label",
        "list_alt",
        "apps",
        "widgets",
      ]),
    ],
  },
];

export const ACCOUNT_ICONS = ACCOUNT_ICON_GROUPS.flatMap(
  (group) => group.icons,
);

export const ACCOUNT_COLORS = [
  "#70d2eb",
  "#ef5350",
  "#ec407a",
  "#ab47bc",
  "#7e57c2",
  "#5c6bc0",
  "#42a5f5",
  "#26c6da",
  "#26a69a",
  "#66bb6a",
  "#9ccc65",
  "#d4e157",
  "#ffee58",
  "#ffca28",
  "#ffa726",
  "#ff7043",
  "#8d6e63",
  "#78909c",
  "#bdbdbd",
  "#ffffff",
];

export function colorForeground(hex: string) {
  const rgb = [1, 3, 5]
    .map((start) => parseInt(hex.slice(start, start + 2), 16) / 255)
    .map((value) =>
      value <= 0.04045 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4,
    );
  return rgb[0] * 0.2126 + rgb[1] * 0.7152 + rgb[2] * 0.0722 > 0.179
    ? "#000000"
    : "#ffffff";
}
